from django.urls import path
from . import views
from . import admin_portal_views, faculty_portal_views, learner_portal_views


urlpatterns = [
    path('', views.render_login_page, name="login"),
    path('doLogin/', views.process_login_request, name="doLogin"),
    path('doLogin', views.process_login_request),
    path('get_user_details/', views.fetch_user_details, name="get_user_details"),
    path('logout_user/', views.process_logout_request, name="logout_user"),
    path('logout_user', views.process_logout_request),
    path('admin_home/', admin_portal_views.render_admin_dashboard, name="admin_home"),
    path('admin_home', admin_portal_views.render_admin_dashboard),
    path('add_staff/', admin_portal_views.render_staff_creation_form, name="add_staff"),
    path('add_staff_save/', admin_portal_views.create_staff_account, name="add_staff_save"),
    path('manage_staff/', admin_portal_views.render_staff_directory, name="manage_staff"),
    path('edit_staff/<staff_id>/', admin_portal_views.render_staff_editor, name="edit_staff"),
    path('edit_staff_save/', admin_portal_views.update_staff_account, name="edit_staff_save"),
    path('delete_staff/<staff_id>/', admin_portal_views.remove_staff_account, name="delete_staff"),
    path('add_course/', admin_portal_views.render_course_creation_form, name="add_course"),
    path('add_course_save/', admin_portal_views.create_course_record, name="add_course_save"),
    path('manage_course/', admin_portal_views.render_course_directory, name="manage_course"),
    path('edit_course/<course_id>/', admin_portal_views.render_course_editor, name="edit_course"),
    path('edit_course_save/', admin_portal_views.update_course_record, name="edit_course_save"),
    path('delete_course/<course_id>/', admin_portal_views.remove_course_record, name="delete_course"),
    path('manage_session/', admin_portal_views.render_session_directory, name="manage_session"),
    path('add_session/', admin_portal_views.render_session_creation_form, name="add_session"),
    path('add_session_save/', admin_portal_views.create_session_record, name="add_session_save"),
    path('edit_session/<session_id>', admin_portal_views.render_session_editor, name="edit_session"),
    path('edit_session_save/', admin_portal_views.update_session_record, name="edit_session_save"),
    path('delete_session/<session_id>/', admin_portal_views.remove_session_record, name="delete_session"),
    path('add_student/', admin_portal_views.render_student_creation_form, name="add_student"),
    path('add_student_save/', admin_portal_views.create_student_account, name="add_student_save"),
    path('edit_student/<student_id>', admin_portal_views.render_student_editor, name="edit_student"),
    path('edit_student_save/', admin_portal_views.update_student_account, name="edit_student_save"),
    path('manage_student/', admin_portal_views.render_student_directory, name="manage_student"),
    path('delete_student/<student_id>/', admin_portal_views.remove_student_account, name="delete_student"),
    path('add_subject/', admin_portal_views.render_subject_creation_form, name="add_subject"),
    path('add_subject_save/', admin_portal_views.create_subject_record, name="add_subject_save"),
    path('manage_subject/', admin_portal_views.render_subject_directory, name="manage_subject"),
    path('edit_subject/<subject_id>/', admin_portal_views.render_subject_editor, name="edit_subject"),
    path('edit_subject_save/', admin_portal_views.update_subject_record, name="edit_subject_save"),
    path('delete_subject/<subject_id>/', admin_portal_views.remove_subject_record, name="delete_subject"),
    path('check_email_exist/', admin_portal_views.verify_email_availability, name="check_email_exist"),
    path('check_username_exist/', admin_portal_views.verify_username_availability, name="check_username_exist"),
    path('student_feedback_message/', admin_portal_views.render_student_feedback_queue, name="student_feedback_message"),
    path('student_feedback_message_reply/', admin_portal_views.save_student_feedback_reply, name="student_feedback_message_reply"),
    path('staff_feedback_message/', admin_portal_views.render_staff_feedback_queue, name="staff_feedback_message"),
    path('staff_feedback_message_reply/', admin_portal_views.save_staff_feedback_reply, name="staff_feedback_message_reply"),
    path('student_leave_view/', admin_portal_views.render_student_leave_queue, name="student_leave_view"),
    path('student_leave_approve/<leave_id>/', admin_portal_views.approve_student_leave_request, name="student_leave_approve"),
    path('student_leave_reject/<leave_id>/', admin_portal_views.reject_student_leave_request, name="student_leave_reject"),
    path('staff_leave_view/', admin_portal_views.render_staff_leave_queue, name="staff_leave_view"),
    path('staff_leave_approve/<leave_id>/', admin_portal_views.approve_staff_leave_request, name="staff_leave_approve"),
    path('staff_leave_reject/<leave_id>/', admin_portal_views.reject_staff_leave_request, name="staff_leave_reject"),
    path('admin_view_attendance/', admin_portal_views.render_admin_attendance_view, name="admin_view_attendance"),
    path('admin_get_attendance_dates/', admin_portal_views.fetch_admin_attendance_dates, name="admin_get_attendance_dates"),
    path('admin_get_attendance_student/', admin_portal_views.fetch_admin_attendance_students, name="admin_get_attendance_student"),
    path('admin_profile/', admin_portal_views.render_admin_profile, name="admin_profile"),
    path('admin_profile_update/', admin_portal_views.update_admin_profile, name="admin_profile_update"),
    path('staff_home/', faculty_portal_views.render_staff_dashboard, name="staff_home"),
    path('staff_home', faculty_portal_views.render_staff_dashboard),
    path('staff_take_attendance/', faculty_portal_views.render_attendance_capture, name="staff_take_attendance"),
    path('get_students/', faculty_portal_views.fetch_subject_students, name="get_students"),
    path('save_attendance_data/', faculty_portal_views.persist_attendance_records, name="save_attendance_data"),
    path('staff_update_attendance/', faculty_portal_views.render_attendance_update, name="staff_update_attendance"),
    path('get_attendance_dates/', faculty_portal_views.fetch_attendance_date_options, name="get_attendance_dates"),
    path('get_attendance_student/', faculty_portal_views.fetch_attendance_student_rows, name="get_attendance_student"),
    path('update_attendance_data/', faculty_portal_views.persist_attendance_updates, name="update_attendance_data"),
    path('staff_apply_leave/', faculty_portal_views.render_staff_leave_form, name="staff_apply_leave"),
    path('staff_apply_leave_save/', faculty_portal_views.submit_staff_leave_request, name="staff_apply_leave_save"),
    path('staff_feedback/', faculty_portal_views.render_staff_feedback_form, name="staff_feedback"),
    path('staff_feedback_save/', faculty_portal_views.submit_staff_feedback, name="staff_feedback_save"),
    path('staff_profile/', faculty_portal_views.render_staff_profile, name="staff_profile"),
    path('staff_profile_update/', faculty_portal_views.update_staff_profile, name="staff_profile_update"),
    path('staff_add_result/', faculty_portal_views.render_result_entry, name="staff_add_result"),
    path('staff_add_result_save/', faculty_portal_views.persist_student_result, name="staff_add_result_save"),
    path('student_home/', learner_portal_views.render_student_dashboard, name="student_home"),
    path('student_home', learner_portal_views.render_student_dashboard),
    path('student_view_attendance/', learner_portal_views.render_student_attendance_lookup, name="student_view_attendance"),
    path('student_view_attendance_post/', learner_portal_views.show_student_attendance_window, name="student_view_attendance_post"),
    path('student_apply_leave/', learner_portal_views.render_student_leave_form, name="student_apply_leave"),
    path('student_apply_leave_save/', learner_portal_views.submit_student_leave_request, name="student_apply_leave_save"),
    path('student_feedback/', learner_portal_views.render_student_feedback_form, name="student_feedback"),
    path('student_feedback_save/', learner_portal_views.submit_student_feedback, name="student_feedback_save"),
    path('student_profile/', learner_portal_views.render_student_profile, name="student_profile"),
    path('student_profile_update/', learner_portal_views.update_student_profile, name="student_profile_update"),
    path('student_view_result/', learner_portal_views.render_student_results, name="student_view_result"),
]
